### PR TITLE
[Proposal] Custom Type Converters for auto mapping - Don't Merge

### PR DESCRIPTION
**Pull request by neildobson-au**
I've discovered when working with Neo4j driver, they have added new NET types including [ZonedDateTime](https://github.com/neo4j/neo4j-dotnet-driver/blob/1.7/Neo4j.Driver/Neo4j.Driver/V1/Types/ZonedDateTime.cs) which allows for storage of high-precision date values in the database. To convert from DateTimeOffset you must pass it via the constructor. To obtain a converted DateTimeOffset you must call the **ToDateTimeOffset** method. Unfortunately this means there's no simple way of converting between the two types using **ConvertTo** or **FromObjectDictionary**.

My proposal is to introduce custom type converters via **ICustomTypeConverter** and perhaps hold a static list of these converters which are evaluated when using the above conversion methods.

```csharp
public interface ICustomTypeConverter
{
    bool CanConvert(object from, Type toType);
    object ConvertFrom(object from);
}
```

Let's take a simplified ZonedDateTime as an example:

```csharp
public class WrappedDateTimeOffset
{
    private readonly DateTimeOffset dateTimeOffset;

    public WrappedDateTimeOffset(DateTimeOffset dateTimeOffset)
    {
        this.dateTimeOffset = dateTimeOffset;
    }

    public DateTimeOffset ToDateTimeOffset()
    {
        return dateTimeOffset;
    }
}
```
When an instance of WrappedDateTimeOffset is found, it should be straightforward to convert it to DateTimeOffset using an ICustomTypeConverter:

```csharp
public class WrappedDateTimeOffsetToDateTimeOffsetConverter : ICustomTypeConverter
{
    public bool CanConvert(object from, Type toType)
    {
        return from is WrappedDateTimeOffset && 
               toType == typeof(DateTimeOffset);
    }

    public object ConvertFrom(object from)
    {
        return (from as WrappedDateTimeOffset)?.ToDateTimeOffset();
    }
}
```
I've created a static class called SsConfig to hold the static collection of custom type converters.
```csharp
public static class SsConfig
{
    static SsConfig()
    {
        CustomTypeConverters = new List<ICustomTypeConverter>();
    }

     public static List<ICustomTypeConverter> CustomTypeConverters { get; }
}
```
Now before converting the source object we need to register the type converter.
```csharp
SsConfig.CustomTypeConverters.Add(new WrappedDateTimeOffsetToDateTimeOffsetConverter());
```
Now we can automatically convert from WrappedDateTimeOffset to DateTimeOffset:
```csharp
var personWithWrappedDateOfBirth = new
{
    FirstName = "Foo",
    LastName = "Bar",
    DateOfBirth = new WrappedDateTimeOffset(
        new DateTimeOffset(1971, 3, 23, 4, 30, 0, TimeSpan.Zero))
};

var personWithDoB = personWithWrappedDateOfBirth.ConvertTo<PersonWithDateOfBirth>();
```
### Issues

1. Name of the class which holds the collection may not fit with current naming conventions.
2. Code pathways differ when using ConvertTo and FromObjectDictionary meaning the check and usage of the converters had to be implemented twice.
3. There may be a performance hit because each ICustomTypeConverter.CanConvert is always evaluated for each property to be converted.
4. There's no scoping mechanism so once its set you can't remove it. This had implications when writing tests and lead to adding a Clear method used in test Setup.
5. There is already a AssignmentEntry.ConvertValueFn but I can't seem to leverage this mechanism.

### CODE REVIEW

**Comment by mythz** [comment]
This implementation is inefficient and fairly disruptive so I've rewritten it in [this commit](https://github.com/ServiceStack/ServiceStack.Text/commit/0959603f8b4fb553d80603d890b400d770cca9b1) so it doesn't introduce any new interfaces or create a new `SsConfig` config class, the converters are looked up by key which is more efficient then executing every converter each time to determine if the converter applies.

The API for registering a converter looks like:

```csharp
AutoMappingUtils.RegisterConverter((WrappedDateTimeOffset from) => from.ToDateTimeOffset());
AutoMappingUtils.RegisterConverter((DateTimeOffset from) => new WrappedDateTimeOffset(from));
```

There's also `AutoMappingUtils.Reset()` API you can use to clear all converters and AutoMapping caches.

This change is available from v5.4.1 that's now [available on MyGet](https://docs.servicestack.net/myget).

**Comment by mythz** [comment]
FYI this has been renamed to `AutoMapping.RegisterConverter` in latest v5.4.1. 

Support for converters and "AutoMapping.IgnoreMapping` has also been improved, see [Customer Forums post](https://forums.servicestack.net/t/avoid-invalidcastexception-when-using-convertto-method/6926/3?u=mythz) and tests in [AutoMappingCustomConverterTests.cs](https://github.com/ServiceStack/ServiceStack.Text/blob/master/tests/ServiceStack.Text.Tests/AutoMappingCustomConverterTests.cs)

**Comment by neildobson-au** [comment]
Thank you for the update. The whole RegisterConverter API was a much better solution than what I originally proposed. Thanks for implementing.

Separately I'm eager to get [Neo4jMapper](https://github.com/barnardos-au/Neo4jMapper) released so that I can start writing about it (and the awesome ServiceStack framework). The benchmarks are telling me this is by far the fastest way to use Neo4j on NET. Any ideas when the ServiceStack.Text might be available on nuget?

**Comment by mythz** [comment]
We don't commit to ETAs but my best guess is around ~2-4 weeks.

**Pull request closed without merging**
