### PR TITLE
BaseConvert method should handle negative integers and throw exception when wrong data supplied

### PR DESCRIPTION
**Pull request by AlexOldest**
Test block:
//.....
string s = null;
try
{
s = StringExtensions.BaseConvert("-212", 3, 10);
WriteLine(s);
s = StringExtensions.BaseConvert("312", 3, 10);
}
catch (Exception ex)
{
Console.WriteLine(ex.Message);
}
//.....

### CODE REVIEW

**Comment by mythz** [comment]
Hi Alex,

Cheers for this, can you [approve the Contributor License Agreement](https://docs.google.com/forms/d/16Op0fmKaqYtxGL4sg7w_g-cXXyCoWjzppgkuqzOeKyk/viewform) so we can merge this, thx.

Could you resend this PR without using C# 6 syntax and to use spaces instead of tabs to stick to the existing code style so that the diffs can show exactly what's changed, thx.

**Comment by AlexOldest** [comment]
Hi Demis,
Thank you for your response. I am new to GitHub but appreciate it very much.
I also appreciate your skill and efforts in creating and supporting ServiceStack.Text library. I intend to learn and use it as a primer when teaching students.
Help me, I have made a change to my first commit, but can't find out how to push it up.

**Comment by AlexOldest** [comment]
I think that it would be easier to attach a new version of StringExtensions.BaseConvert extension-method
[BaseConvert.txt](https://github.com/ServiceStack/ServiceStack.Text/files/35476/BaseConvert.txt)

**Comment by mythz** [comment]
Hi Alex, 

No worries I just applied the changes manually in this commit: https://github.com/ServiceStack/ServiceStack.Text/commit/b06246a80ead5430e6e5d77e95b0095baa3a40ca

You can get this change on v4.0.47 [MyGet pre-release packages](https://github.com/ServiceStack/ServiceStack/wiki/MyGet) now, or you can wait till tomorrow when we should be deploy the next v4.0.48 official release to NuGet.

**Pull request closed without merging**
