### PR TITLE
Ignore unmatched { or [ in values when CsvReader.ParseFields()

### PR DESCRIPTION
**Pull request by darkthread**
Modify EatValue() to pass these tests
`            
            Assert.That(CsvReader.ParseFields("{A,B"), Is.EqualTo(new[] { "{A", "B" }));
            Assert.That(CsvReader.ParseFields("{A},B"), Is.EqualTo(new[] { "{A}", "B" }));
            Assert.That(CsvReader.ParseFields("[A,B"), Is.EqualTo(new[] { "[A", "B" }));
            Assert.That(CsvReader.ParseFields("[A],B"), Is.EqualTo(new[] { "[A]", "B" }));
            Assert.That(CsvReader.ParseFields("[{A],B"), Is.EqualTo(new[] { "[{A]", "B" }));
            Assert.That(CsvReader.ParseFields("[A},B"), Is.EqualTo(new[] { "[A}", "B" }));
            Assert.That(CsvReader.ParseFields("[[A],B"), Is.EqualTo(new[] { "[[A]", "B" }));
            Assert.That(CsvReader.ParseFields("A],B"), Is.EqualTo(new[] { "A]", "B" }));
            Assert.That(CsvReader.ParseFields("A},B"), Is.EqualTo(new[] { "A}", "B" }));`

### CODE REVIEW

**Comment by mythz** [comment]
Can you [squash all these commits into 1 commit](https://stackoverflow.com/a/5201642/85785) so there's only a single commit that shows the changes. An alternative to squashing commits is to create a new fork from master and apply the changes on top in a single commit.

**Comment by darkthread** [comment]
@mythz I just squashed my commits into one, am I doing it right? 
(my git skill stays at junior level, feel free to tell me if I didn't use the proper tool.)

**Comment by mythz** [comment]
Not exactly (there's now 6 commits total), but I should be able to squash the commits on my side. Can you [approve the Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLSc-vKvdOx5lXGqmy6fkdCj-N0pALkVCx7QHYXojAuDSv_enNA/viewform) so we can merge this, thx.

An alternative/easier approach can be to start fresh from a clean fork and apply your changes to that, but I should be able to squash the PR on my side.

**Comment by darkthread** [comment]
Agreement approved. Thanks for sharing commit merge tips.

**Comment by mythz** [comment]
Cheers 👍 this change is available from v4.5.13 that's now [available on MyGet](http://docs.servicestack.net/myget).

**Pull request merged**
