### PR TITLE
Fix for dictionary object with empty string

### PR DESCRIPTION
**Pull request by IntegrationCrm**
Csv serialisation of collection of Dictionary or Dynamic types with empty string generates index out of range exception.

### CODE REVIEW

**Comment by mythz** [comment]
Cheers 👍 thx for the PR + test!

**Comment by IntegrationCrm** [comment]
You're welcome! Thanks for the great library 👍

**Comment by MortenChristiansen** [comment]
@mythz Do you have an idea about the timeframe for when this is released? We have a data export that has begun breaking and we would really like to avoid custom code to handle this.

**Comment by mythz** [comment]
pre-release packages are available on MyGet now: http://docs.servicestack.net/myget

V5 on MyGet is technically complete now, we’re working on upgrading existing projects now before the next release, hopefully next week.

**Comment by MortenChristiansen** [comment]
Thanks, that sounds great.

**Pull request merged**
