### PR TITLE
Add JsScope.PreserveUtc. When true overrides standard behavior of con…

### PR DESCRIPTION
**Pull request by rsafier**
…verting all DateTime into DateTimeKind.Local. Incoming UTC dates will be kept in DateTimeKind.Utc

### CODE REVIEW

**Comment by mythz** [comment]
The configuration for Dates is becoming a confusing mess, when would you this where `JsConfig.AlwaysUseUtc` wouldn't suffice?

Also does this behavior have to be limited to Utc, i.e. can it be called PreserveDateTime and prevent conversion of any DateTime Kind?

**Comment by rsafier** [comment]
I agree the Date stuff is confusing, took a while to just develop our current setup after testing out the array of flags and not finding a great fit for our setup (which is far from optimal, but some things are out of my control).

Short version: `PreserveDateTime` sounds good and would work for what I'm attempting to do.

Expanded:

What would truly solve my issues would be a way to apply an attribute onto a DTO field which would flag the DateTime serialization to completely ignore timezone info, but having looked at the code it wasn't a easy fit, nor do I think many people need this. 

I ended up with a custom `JsConfig<DateTime>` deserializer solution, but it is global, and can cause issue integrating with other services, especially outbound ServiceClients calling other services which don't need this funky encoding. Its been working for the past 6 months, but is a bit clunky.
Standardizing on `AlwaysUseUtc` would be great, but realistically not going to happen anytime soon in our code base or clients.

I can probably get all my new development at least to comply to encoding the fields which should stay fixed into `DateTimeKind.Utc` before they send the request so end-to-end things will just work with only 2 lines of config and if we need a different `DateTime` structure for other requests it can still be scoped. 

I only tested this against being set as `JsConfig.DateHandler = DateHandler.ISO8601` and I am not quite sure what the `DateTimeKind.Unspecified` is being converted to with this patch.

**Comment by mythz** [comment]
The problem with this is that it increases the surface area making both the public API, implementation and behavior even more confusing, increasing the maintenance burden and hindering future refactoring. I would really like to avoid adding more complexity to the built-in DateTime Serialization, I'd rather focus on making it easier to substitute the existing implementation entirely.

A way to get completely around the built-in implementation is as you've assumed to use `JsConfig<DateTime>` which would be my preference for anyone that needs this.

But in this case I think having a `PreserveDateTime` or `SkipDateTimeConversion` and remove the limitation on Utc would be acceptable as it's something new that others may want, I also never want to later add a `PreserveLocal` or `PreserveUnspecified` to match this feature.

**Comment by rsafier** [comment]
`SkipDateTimeConversion` makes sense to me, assuming I'm interpreting it correctly as: 
DateTime's with TZ info are encoded as kind `Local` and without any correction, Utc as `Utc`, missing TZ as `Unspecified`, sans correction. This would be more useful. Can you address this or do you wish me to refactor this pull?

**Comment by mythz** [comment]
Yep I think that behavior would be ok. Could you please refactor the PR, thx.

**Comment by rsafier** [comment]
I'm closer but for some reason now the Can_Write_QueryString test is failing, I couldn't quite seem to figure out where that is happening, Prior to realizing I had to merge conflicts everything was working.

**Comment by mythz** [comment]
Hi Richard, can you try pulling the latest commit to see if that makes a difference?

**Comment by rsafier** [comment]
Sure. It looks like I was going down the same direction I was just starting to explore.

**Comment by rsafier** [comment]
Passed all the tests now.

**Comment by mythz** [comment]
thx Richard, I'll pull this in and probably do some slight code re-factoring/cleanup

**Comment by mythz** [comment]
hmm, I'm getting a lot of failed tests - are you sure they were all passing?

**Comment by rsafier** [comment]
I was having some of the tests fail on the first pass, but run on 2nd pass, wasn't sure if it was something on my setup. I'm still a fairly new to unit tests, and git for that matter.

**Comment by mythz** [comment]
ok no worries looks like it was just due to the configuration leaking into different tests since the setting wasn't reset back at the end of the test, resolved with:

https://github.com/ServiceStack/ServiceStack.Text/commit/773d90a1e272ae546892bed0845d5b1365b55675

**Pull request merged**
