### PR TITLE
optional mapping for ToObjectDictionary

### PR DESCRIPTION
**Pull request by bnayae**
Similar needs as 
https://github.com/ServiceStack/ServiceStack/pull/1215

need to handle enum's properties

### CODE REVIEW

**Comment by bnayae** [comment]
I can't compile or test it on my machine.
I'm getting this error:
error CS0006: Metadata file 'c:\ServiceStack.Text\tests\Northwind.Common\bin\Debug\net45\Northwind.Common.dll' could not be found
what do I miss?

**Comment by mythz** [comment]
Have you built Northwind.Common?

**Comment by bnayae** [comment]
I was doing re-build solution a few time when the error occurs.
When I was building Northwind.Common directly it worked out.
Mabye it's a good idea to check the project dependency definition.
Anyway I was fixing the tests.

**Comment by mythz** [comment]
Northwind.Common has a lot of source code which never changes which is why it's not built by default, it just needs to be built once.

BTW thx for the PR!

**Pull request merged**
